"""Generate local Markdown security posture reports."""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from devsecops_coral.models import RecommendedAction


def generate_markdown(*, actions: list[RecommendedAction]) -> dict[str, Any]:
    """Write a Markdown security posture report to ``./reports/``.

    Args:
        actions: Current list of recommended (and possibly executed) actions.

    Returns:
        Dict with keys ``path`` (file path written) and ``bytes`` (file size).
    """
    reports_dir = Path("reports")
    reports_dir.mkdir(exist_ok=True)

    date_str = datetime.date.today().isoformat()
    filename = reports_dir / f"posture-{date_str}.md"

    lines = [
        f"# Security Posture Report — {date_str}",
        "",
        "Generated by **CoralSentinel** — cross-stack security operations agent.",
        "",
        "## Recommended Actions",
        "",
    ]

    for action in actions:
        status_badge = f"[{action.status.value.upper()}]"
        urgent_tag = " ⚠️ URGENT" if action.urgent else ""
        lines += [
            f"### {action.id}. {action.title}{urgent_tag}",
            f"- **Type:** {action.type.value}",
            f"- **Severity:** {action.severity}",
            f"- **Status:** {status_badge}",
        ]
        if action.cve:
            lines.append(f"- **CVE:** [{action.cve}](https://osv.dev/vulnerability/{action.cve})")
        if action.package:
            lines.append(f"- **Package:** `{action.package}`")
        lines.append(f"- **Detail:** {action.detail}")
        if action.result:
            lines.append(f"- **Result:** {action.result}")
        lines.append("")

    lines += ["---", f"*Generated: {datetime.datetime.now().isoformat()}*"]
    content = "\n".join(lines)
    filename.write_text(content, encoding="utf-8")
    return {"path": str(filename), "bytes": len(content)}
